name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Project
        run: make build
        env:
          GOBIN: ${{ github.workspace }}/.bin

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-harness
          path: ${{ github.workspace }}/.bin/nginx-harness

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-harness
          path: ${{ github.workspace }}/.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/.bin/nginx-harness

  container:
    name: Build and Push Container Image
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-harness
          path: ${{ github.workspace }}/.bin

      - name: Build and publish a image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Containerfile

